### ISSUE TITLE
Intake Subsystem

### ISSUE THREAD

**Issue by msoucy** [chopshop-166/frc-2020#11]
- [x] List of Inputs (Sensors)
- [x] List of Outputs (Motors, Pneumatics)
    - [x] `RobotMap`
- [x] List of Actions (Commands)
- [x] Integrate Commands into Robot class

**Comment by ghost** [comment]
- Start the command to run Pierre

- Then, when Pierre ends, the intake command starts until there is no longer the presence of a ball within it

**Comment by Rohan-Sreenivasan** [comment]
Commands
-Deploy intake
-retract intake
-intake one ball
-roll outward, rid of balls

**Comment by bot190** [comment]
I realized we probably want a command that will lower the intake and run it backwards. This will be useful for pushing balls out of our way instead of potentially driving over them.

**Comment by bot190** [comment]
Basic intake functionality is working, closing this.
