### ISSUE TITLE
Control Panel Subsystem

### ISSUE THREAD

**Issue by msoucy** [chopshop-166/frc-2020#12]
- [x] List of Inputs (Sensors)
- [x] List of Outputs (Motors, Pneumatics)
    - [x] `RobotMap`
- [x] List of Actions (Commands)
- [x] Integrate Commands into Robot class

**Comment by Rohan-Sreenivasan** [comment]
Commands: 
Spin in between 3-5 rotations
Spin to given color
Spin with `DoubleSupplier`

**Comment by andrewmartin5** [comment]
No longer relavent for the 2021 game
