### ISSUE TITLE
Indexer Subsystem

### ISSUE THREAD

**Issue by msoucy** [chopshop-166/frc-2020#14]
- [x] List of Inputs (Sensors)
- [x] List of Outputs (Motors, Pneumatics)
    - [x] `RobotMap`
- [ ] List of Actions (Commands)
- [ ] Integrate Commands into Robot class

**Comment by Rohan-Sreenivasan** [comment]
Commands: 
-Roll Balls to shooter
-Roll balls outward

**Comment by bot190** [comment]
Indexer is fully functional, closing this.
