### ISSUE TITLE
More Drive things to do

### ISSUE THREAD

**Issue by andrewmartin5** [chopshop-166/frc-2020#25]
- [x] Test NEO encoder resolution

- [x] Write code to use the IMU!

- [ ] Attempt to implement velocity PID

- [x] Tune turn to angle PID

- [ ] Path following for autonomous

**Comment by bot190** [comment]
You can find some more details about the IMU:
http://www.ctr-electronics.com/sensors/gadgeteer-imu-module-pigeon.html

**Comment by msoucy** [comment]
https://github.com/chopshop-166/frc-2019/blob/2020-Update/src/main/java/frc/robot/subsystems/Drive.java#L173 PID Controller from last year (ish)

**Comment by GrantPerkins** [comment]
With all of the free time you have now, trajectory following should really be a priority of yours. It's not terribly hard to get working in my opinion.

**Comment by msoucy** [comment]
I agree that trajectory following is a priority, which is why we have it on this list. Unfortunately, due to the pandemic we are unable to meet to refine any trajectory code. We'll keep this in mind moving forward and into the summer.
