### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by AustinFortunato** [chopshop-166/frc-2020#38]
ok... uh everyone update your block comments from the start of the year!
Cool, then:
- [ ] Vision documentation overview (show how we implemented it)
- [X] RPM documentation

**Comment by AustinFortunato** [comment]
Got RPM docs - https://github.com/chopshop-166/frc-2020/wiki/Converting-Feet-to-RPM

**Comment by AustinFortunato** [comment]
- [ ] hi

**Comment by andrewmartin5** [comment]
Vision is currently being held off in favour of glowworm

**Comment by msoucy** [comment]
I think this is safe to close now
