### ISSUE TITLE
Team 3045 Code Review Party

### ISSUE THREAD

**Issue by PicklesTheFrog** [chopshop-166/frc-2020#53]
Hello Team 166,
     Our team have a less advanced software group so we may not have the best feedback. With that, here's our feedback:
     - We really like your vision code. We use auto generated code from Grip as our vision and add onto it. What are the benefits of making everything from scratch? 
     - Your code is really neat and readable. Very cool use of existing commands. 
     - You guys have a really nice elevator system. 

- Team 3045

**Comment by msoucy** [comment]
Thank you, we appreciate the feedback! We hope that you found something that you could learn from.

One reason to make the vision code from scratch, is to be able to use special features of an unusual camera (`realsense2` in our case). It also allows a finer control over the vision pipeline. A downside, however, is that it usually involves more setup, especially if you want parameters to be altered for different venues. It's a tradeoff that we're looking at - the student who did vision most this year, is documenting the setup involved for use on a raspberry pi to avoid the discovery process for future years.
