### ISSUE TITLE
Lift Subsystem

### ISSUE THREAD

**Issue by msoucy** [chopshop-166/frc-2020#8]
- [x] List of Inputs (Sensors)
- [x] List of Outputs (Motors, Pneumatics)
    - [x] `RobotMap`
- [x] List of Actions (Commands)
- [x] Integrate Commands into Robot class

**Comment by andrewmartin5** [comment]
SUB REVIEW Lift Subsystem What Does It Do? 
1) Raises and lowers lift Manually using two different motors in sync 
2) Uses ratchet mechanism to break
 
 What Modes Does It Have? 
1) Up (Extend) 
2) Down (Retract) 
3) Break (Ratchet)

 What Interactions Does It Have With Other Subsystems? 
1) None?
 
 How Is It Triggered? 
1) User Input
 
 Does It Store Any State? 
1) isBreaked

**Comment by DavidDesfosse** [comment]
We also want modes to be able to go to the height that the bar is at when it is neutral and at the top, and then Sean can make adjustments from there. It should also store states for when it is at the highest point it can go and the lowest point it can go so we don't break it

**Comment by Rohan-Sreenivasan** [comment]
Commands:
-Lift to high position
-Lift to middle position
-Lift to low position
-Use triggers to lift to any height (consider as default)

**Comment by bot190** [comment]
Basic lift functionality is working, closing this.
