### ISSUE TITLE
Shooter Subsystem

### ISSUE THREAD

**Issue by msoucy** [chopshop-166/frc-2020#9]
- [x] List of Inputs (Sensors)
- [x] List of Outputs (Motors, Pneumatics)
    - [x] `RobotMap`
- [x] List of Actions (Commands)
- [x] Integrate Commands into Robot class

**Comment by Rohan-Sreenivasan** [comment]
Commands:
-Shoot a ball
-Shoot all balls

**Comment by bot190** [comment]
Basic shooter functionality is working, closing this.
